name: plasmer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.10.4
  - biopython
  - seqkit==2.2.0
  - perl==5.26.2
  - kmer-db==1.9.4
  - prodigal==2.6.3
  - HMMER==3.3.2
  - BLAST==2.10.1
  - INFERNAL==1.1.4
  - diamond==2.0.15
  - Parallel
  - Kraken2==2.1.2
  - R==4.2.0
  - r-randomforest==4.7_1.1
  - r-hash
