package:
    name: Plasmer
    version: 0.0

build:
    skip: True # [py<35]

source:
    git_url: https://github.com/nekokoe/Plasmer.git

requirements:
    build:
        - python
    run:
        - python
        - 'numpy <=1.15.0'
        - 'scipy >=1.1.0'
        - 'matplotlib >=2.2.3'
 
        
about:
    home: https://github.com/nekokoe/Plasmer
    license: MIT
