name: Build and push conda
on:
  push:
    branches:
      - "main"
    
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: iskoldt-X/conda-publish-action@v2
      with:
        subdir: '.'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'linux-64'